# use python base image from docker hub
FROM python
# set a working directory
WORKDIR /app
# copy everything into local folder
COPY . /app
# command to execute when container is started
CMD ["python","rng.py"]