version: "3.8"

services:
  server:
    image: 'nginx:stable-alpine'
    ports:
      - "8000:80"
    # copy the nginx file from the path provided(./nginx/nginx.conf):to the path inside docker container(/etc/nginx/nginx.conf:ro)
    # ro - read only so container can never change configuration
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  # php:
  # mysql:
  # composer:
  # artisan:
  # npm:    