# for yaml file we must always start with version
version: '3.8'
services:
# containers
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
    # custom container name
    # container_name: mongodb  
    # specify env variables
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME:max
    #   MONGO_INITDB_ROOT_PASSWORD:secret
    # specify environment variables in an env file
    env_file:
      - ./env/mongo.env
# compose commands for node file
  backend:
  # short form for which image the backend be based
    build: ./backend
    ports:
      - '80:80'
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env 
    # only after the mongodb compose is completed the backend compose should be started
    depends_on:
      - mongodb
  # long form for which image the backend be based
  # build:
      # context: ./backend
      # dockerfile: Dockerfile
      # args:
      #   some-arg: 1
      # ports:
      #   - '80:80'
# compose commands for react
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    # run the app in interactive mode
    stdin_open: true
    tty: true
    depends_on:
      - backend
    
volumes:
  data:
  logs: